// Command palettegen writes agk console's palette, palette.go, from the design system's token
// file, which console/vendor/tokens.json holds as agentiik/design publishes it. The values are
// never typed into agk: the terminal is drawn from the copy the web console is drawn from, at the
// same version, so the two cannot drift apart.
//
// Each colour of each ground is written with its nearest of the 256 colours a terminal without
// true colour shows, by CIE Lab distance, as the documentation's colour table gives them: the
// distance a person sees, where a distance in RGB would match a green to a grey.
//
// Run by go generate in package console; the test beside it fails where palette.go is not what
// this writes from the token file.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"math"
	"os"
	"slices"
	"strconv"
)

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: palettegen TOKENS.JSON PALETTE.GO")
		os.Exit(2)
	}
	tokens, err := os.ReadFile(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	out, err := Generate(tokens)
	if err != nil {
		fmt.Fprintf(os.Stderr, "%s: %s\n", os.Args[1], err)
		os.Exit(1)
	}
	if err := os.WriteFile(os.Args[2], out, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// Generate is palette.go as the token file given makes it.
func Generate(tokens []byte) ([]byte, error) {
	var file struct {
		Colour map[string]map[string]string `json:"colour"`
	}
	if err := json.Unmarshal(tokens, &file); err != nil {
		return nil, err
	}
	var b bytes.Buffer
	b.WriteString(`// Code generated by palettegen from console/vendor/tokens.json. DO NOT EDIT.

package console

// The design system's colours on each ground, each with its nearest of the 256 colours by CIE Lab
// distance: written by palettegen from the token file the web console is drawn from.
var (
`)
	for _, ground := range []string{"dark", "light"} {
		colours := file.Colour[ground]
		if len(colours) == 0 {
			return nil, fmt.Errorf("colour.%s holds no colour", ground)
		}
		names := make([]string, 0, len(colours))
		for name := range colours {
			names = append(names, name)
		}
		slices.Sort(names)
		fmt.Fprintf(&b, "\t%sGround = ground{\n", ground)
		for _, name := range names {
			rgb, err := parse(colours[name])
			if err != nil {
				return nil, fmt.Errorf("colour.%s.%s: %w", ground, name, err)
			}
			fmt.Fprintf(&b, "\t\t%q: {%q, %d},\n", name, colours[name], nearest(rgb))
		}
		b.WriteString("\t}\n")
	}
	b.WriteString(")\n")
	return format.Source(b.Bytes())
}

// parse reads a colour as the token file writes it, #RRGGBB.
func parse(hex string) ([3]uint8, error) {
	if len(hex) != 7 || hex[0] != '#' {
		return [3]uint8{}, fmt.Errorf("%q is not written #RRGGBB", hex)
	}
	var rgb [3]uint8
	for i := range rgb {
		v, err := strconv.ParseUint(hex[1+2*i:3+2*i], 16, 8)
		if err != nil {
			return [3]uint8{}, fmt.Errorf("%q is not written #RRGGBB", hex)
		}
		rgb[i] = uint8(v)
	}
	return rgb, nil
}

// xterm is the colour a terminal draws for each of the 256 from 16 on: the 6 by 6 by 6 cube, then
// the 24 greys. The first sixteen are the terminal's own, set by its theme, so no token is matched
// to one: the sixteen are what a terminal of sixteen colours is drawn with, by name.
func xterm(i int) [3]uint8 {
	if i >= 232 {
		v := uint8(8 + 10*(i-232))
		return [3]uint8{v, v, v}
	}
	levels := [6]uint8{0, 95, 135, 175, 215, 255}
	i -= 16
	return [3]uint8{levels[i/36], levels[i/6%6], levels[i%6]}
}

// nearest is the index of the colour of the 256 closest to rgb by CIE76, the Euclidean distance
// in CIE Lab, the first one where two are as close.
func nearest(rgb [3]uint8) int {
	want := lab(rgb)
	best, bestDistance := 16, math.Inf(1)
	for i := 16; i < 256; i++ {
		got := lab(xterm(i))
		d := 0.0
		for k := range want {
			d += (want[k] - got[k]) * (want[k] - got[k])
		}
		if d < bestDistance {
			best, bestDistance = i, d
		}
	}
	return best
}

// lab is an sRGB colour in CIE L*a*b*, under the D65 white an sRGB screen is calibrated to.
func lab(rgb [3]uint8) [3]float64 {
	var lin [3]float64
	for i, c := range rgb {
		v := float64(c) / 255
		if v <= 0.04045 {
			lin[i] = v / 12.92
		} else {
			lin[i] = math.Pow((v+0.055)/1.055, 2.4)
		}
	}
	x := (lin[0]*0.4124564 + lin[1]*0.3575761 + lin[2]*0.1804375) / 0.95047
	y := lin[0]*0.2126729 + lin[1]*0.7151522 + lin[2]*0.0721750
	z := (lin[0]*0.0193339 + lin[1]*0.1191920 + lin[2]*0.9503041) / 1.08883
	f := func(t float64) float64 {
		if t > 216.0/24389 {
			return math.Cbrt(t)
		}
		return (24389.0/27*t + 16) / 116
	}
	fx, fy, fz := f(x), f(y), f(z)
	return [3]float64{116*fy - 16, 500 * (fx - fy), 200 * (fy - fz)}
}
