// Code generated by palettegen from console/vendor/tokens.json. DO NOT EDIT.

package console

// The design system's colours on each ground, each with its nearest of the 256 colours by CIE Lab
// distance: written by palettegen from the token file the web console is drawn from.
var (
	darkGround = ground{
		"accent":        {"#68AEF5", 75},
		"accentDim":     {"#0F2B46", 235},
		"accentLine":    {"#1C4165", 24},
		"bg":            {"#121212", 233},
		"failed":        {"#E0705A", 167},
		"failedFill":    {"#31190F", 234},
		"failedLine":    {"#5F3023", 95},
		"faint":         {"#777777", 243},
		"line":          {"#2E2E2E", 236},
		"lineStrong":    {"#3E3E3E", 237},
		"muted":         {"#9E9E9E", 247},
		"onAccent":      {"#121212", 233},
		"raised":        {"#222222", 235},
		"running":       {"#68AEF5", 75},
		"succeeded":     {"#5FA773", 72},
		"succeededFill": {"#132A1C", 235},
		"succeededLine": {"#264B33", 23},
		"sunken":        {"#0E0E0E", 233},
		"surface":       {"#1A1A1A", 234},
		"text":          {"#E8E8E8", 254},
		"waiting":       {"#D9A441", 179},
		"waitingFill":   {"#2E2413", 235},
		"waitingLine":   {"#5B461E", 58},
	}
	lightGround = ground{
		"accent":        {"#015DA2", 25},
		"accentDim":     {"#D7E7F9", 254},
		"accentLine":    {"#A5C5E7", 153},
		"bg":            {"#F1F1F1", 255},
		"failed":        {"#B23C1E", 88},
		"failedFill":    {"#F6E1D9", 224},
		"failedLine":    {"#E3B5A7", 181},
		"faint":         {"#888888", 102},
		"line":          {"#DFDFDF", 254},
		"lineStrong":    {"#C6C6C6", 251},
		"muted":         {"#656565", 241},
		"onAccent":      {"#FFFFFF", 231},
		"raised":        {"#FFFFFF", 231},
		"running":       {"#015DA2", 25},
		"succeeded":     {"#2E7D4F", 29},
		"succeededFill": {"#DCEBE0", 254},
		"succeededLine": {"#ADCDB9", 151},
		"sunken":        {"#E9E9E9", 255},
		"surface":       {"#FBFBFB", 231},
		"text":          {"#1D1D1D", 234},
		"waiting":       {"#96660A", 94},
		"waitingFill":   {"#F4EAD3", 230},
		"waitingLine":   {"#DBC69D", 187},
	}
)
